import { RNG, GradientNoise2D, binaryInsert } from './utils.js?v=1.0.4';
import { WorldNameGenerator } from '../names/names.js?v=1.0.4';
import { BIOME_KEYS, BIOMES, POI_TYPES, getProceduralHooks } from './biomes.js?v=1.0.4';
import { generatePoiDescription } from './descriptionGenerator.js?v=1.0.4';

export class WorldEngine {
    constructor(seed, sizeMode, coreType, tectonics, atmosphere, climate, customW = 512, customH = 256, allowMagic = true, landmassType = 'continents') {
        this.seed       = seed;
        this.rng        = new RNG(seed);
        this.sizeMode   = sizeMode;
        this.coreType   = coreType;
        this.tectonics  = tectonics;
        this.atmosphere = atmosphere;
        this.climate    = climate;
        this.allowMagic = allowMagic;
        this.landmassType = landmassType;

        let W = 256;
        if (sizeMode === 'small') W = 128;
        else if (sizeMode === 'medium') W = 256;
        else if (sizeMode === 'large') W = 512;
        else if (sizeMode === 'legendary') W = 1024;
        else if (sizeMode === 'epic') W = 2048;
        else if (sizeMode === 'custom') W = parseInt(customW, 10) || 512;

        this.width  = W;
        this.height = sizeMode === 'custom' ? (parseInt(customH, 10) || 256) : Math.floor(W * 0.5);

        this.nameGen = new WorldNameGenerator(new RNG(seed + '_names'));
        this.nations = [];
        this.cities  = [];
        this.pois    = [];

        this.citiesMap = new Map();
        this.poisMap = new Map();

        // Flat TypedArrays for low-memory overhead (crucial for 2048x1024 grids)
        const size = this.width * this.height;
        this.heightMap   = new Float32Array(size);
        this.tempMap     = new Int8Array(size);
        this.moistureMap = new Uint8Array(size);
        this.aquiferMap  = new Uint8Array(size);
        this.magmaMap    = new Uint8Array(size);
        this.biomeMap    = new Uint8Array(size);
        this.nationMap   = new Int16Array(size);
        this.riverMap    = new Uint8Array(size);
        this.lakeMap     = new Uint8Array(size);
        this.riverPaths  = [];
        this.nationMap.fill(-1);

        // Transparent Grid Proxy: allows world.grid[y][x] to return virtual sector objects lazily
        this.grid = new Proxy([], {
            get: (target, yStr) => {
                const y = parseInt(yStr, 10);
                if (isNaN(y) || y < 0 || y >= this.height) return target[yStr];
                return new Proxy([], {
                    get: (rowTarget, xStr) => {
                        const x = parseInt(xStr, 10);
                        if (isNaN(x) || x < 0 || x >= this.width) return rowTarget[xStr];
                        return this.getSector(x, y);
                    }
                });
            }
        });

        this.atmosphereLayers = [
            { name:'Troposphere',   alt:'0–12 km',        desc:'The weather layer. Contains 75% of atmospheric mass. All weather phenomena occur here.',             temp:'+15°C to −57°C',  pressure:'1.0–0.1 atm' },
            { name:'Stratosphere',  alt:'12–50 km',       desc:'Dry and stable. The ozone layer shields the surface from ultraviolet radiation.',                   temp:'−57°C to −3°C',   pressure:'0.1–0.001 atm' },
            { name:'Mesosphere',    alt:'50–85 km',       desc:'The coldest atmospheric layer. Incoming meteors incandesce and burn up here.',                      temp:'−3°C to −90°C',   pressure:'0.001–0.00001 atm' },
            { name:'Thermosphere',  alt:'85–600 km',      desc:'Ionosphere sub-layer. Solar radiation excites gas particles, creating polar auroras.',              temp:'−90°C to +2500°C',pressure:'Trace' },
            { name:'Exosphere',     alt:'600–10,000 km',  desc:'The outermost atmospheric boundary. Gas molecules escape into interplanetary space here.',          temp:'2500°C (molecular)',pressure:'Near-vacuum' },
            { name:'Magnetosphere', alt:'10,000–60,000 km',desc:'Magnetic field generated by the planetary core. Deflects solar wind and cosmic radiation.',       temp:'Stellar ambient', pressure:'Vacuum' },
        ];

        this.coreLayers = [
            { name:'Crust',          thickness:'5–70 km',        composition:'Silicate rocks (Basalt, Granite, Andesite)',                      state:'Solid',                    temp:'Surface to 900°C' },
            { name:'Lithosphere',    thickness:'80–150 km',      composition:'Brittle crust and rigid upper mantle fused together',              state:'Rigid Solid',              temp:'900–1,200°C' },
            { name:'Asthenosphere',  thickness:'180–250 km',     composition:'Partially molten ductile silicate rock enabling plate motion',     state:'Plastic / Semi-fluid',     temp:'1,200–1,400°C' },
            { name:'Mantle',         thickness:'2,890 km',       composition:'Magnesium-iron silicates (Peridotite, Pyroxenite)',                state:'Viscous Solid / Convecting',temp:'1,400–3,700°C' },
            { name:'Outer Core',     thickness:'2,200 km',       composition:this._coreCompositionName() + ' (liquid)',                          state:'Molten Liquid (Dynamo)',   temp:'3,700–5,000°C' },
            { name:'Inner Core',     thickness:'1,280 km radius',composition:this._coreCompositionName() + ' (crystalline)',                     state:'Crystalline Solid',        temp:'5,000–6,000°C' },
        ];

        this.generate();
    }

    _coreCompositionName() {
        const m = { 'iron-nickel':'Iron-Nickel Alloy', 'silicate':'Silicate Oxide Matrix',
                    'gold-molten':'Molten Heavy Metals (Au, Pt, U)', 'crystal':'Volatile Energy Crystal' };
        return m[this.coreType] || 'Iron-Nickel Alloy';
    }

    getSector(x, y) {
        const idx = y * this.width + x;
        if (idx < 0 || idx >= this.width * this.height) return null;

        const h = this.heightMap[idx];
        const temp = this.tempMap[idx];
        const moisture = this.moistureMap[idx];
        const aquifer = this.aquiferMap[idx];
        const magmaPct = this.magmaMap[idx];
        const biomeIndex = this.biomeMap[idx];
        const biome = BIOME_KEYS[biomeIndex] || 'Ocean';
        const nationId = this.nationMap[idx];
        const isRiver = this.riverMap[idx] === 1;
        const isLake = this.lakeMap[idx] === 1;

        const latDeg = ((this.height / 2 - y) / (this.height / 2)) * 90;
        const lonDeg = ((x / this.width) - 0.5) * 360;

        const coordKey = `${x},${y}`;
        const city = this.citiesMap.get(coordKey) || null;
        const poi = this.poisMap.get(coordKey) || null;

        // Travel difficulty scale
        let travelSpeed = "Normal Travel (1x)";
        let difficultyValue = 1;
        if (h > 0.82) { travelSpeed = "Impassable Peaks (6x)"; difficultyValue = 8; }
        else if (h > 0.72) { travelSpeed = "Challenging Climb (4x)"; difficultyValue = 6; }
        else if (biome.includes('Ocean') || biome.includes('Sea')) { travelSpeed = "Requires Vessel"; difficultyValue = 9; }
        else if (biome === 'Swamp' || biome === 'Mangrove Swamp' || biome === 'Dune Sea' || biome === 'Obsidian Spireland' || biome === 'Badlands') { travelSpeed = "Difficult Terrain (2x)"; difficultyValue = 4; }
        else if (biome === 'Glacier' || biome === 'Ice Cap') { travelSpeed = "Treacherous Ice (3x)"; difficultyValue = 5; }

        // Survival / Forage probability
        let forageRating = "Moderate (50% chance/day)";
        let foragePct = 50;
        if (biome.includes('Ocean') || biome.includes('Sea')) { forageRating = "Fishing Abundant (80%)"; foragePct = 80; }
        else if (biome === 'Desert' || biome === 'Dune Sea' || biome === 'Ash Wastes' || biome === 'Glacier' || biome === 'Ice Cap' || biome === 'Mana Wastes' || biome === 'Obsidian Spireland' || biome === 'Astral Rift') { forageRating = "Barren Wasteland (0%)"; foragePct = 0; }
        else if (biome === 'Forest' || biome === 'Temperate Rainforest' || biome === 'Fey Wildwood' || biome === 'Bioluminescent Jungle' || biome === 'Oasis') { forageRating = "Sustiful / Rich (90%)"; foragePct = 90; }
        else if (biome === 'Grassland' || biome === 'Alpine Meadow' || biome === 'Valley') { forageRating = "Good Foraging (75%)"; foragePct = 75; }

        // Seeded local minor faction
        let localMinorFaction = "None";
        if (poi && poi.minorFaction) {
            localMinorFaction = poi.minorFaction;
        } else {
            const factionRng = new RNG(this.seed + `_cell_fac_${x}_${y}`);
            if (factionRng.next() < 0.22) {
                const groups = [
                    "The Emerald Druids", "Red Fang Goblin Clan", "Shadow Syndicate",
                    "Aurelian Hermits", "Iron Pick Miner Guild", "Deepwood Rangers", "The Broken Shield Outlaws",
                    "Spell-Warped Cultists", "Crystalline Sentinels", "Fey Court Outriders", "Ghost-light Wanderers"
                ];
                localMinorFaction = factionRng.pick(groups);
            }
        }

        const info = BIOMES[biome] || BIOMES['Ocean'];
        const selfSeed = this.seed;

        return {
            x, y,
            lat: latDeg.toFixed(1),
            lon: lonDeg.toFixed(1),
            height: h,
            temp,
            moisture,
            aquifer,
            magmaPct,
            biome,
            soil: info.soil,
            bedrock: info.bedrock,
            liquid: (biome.includes('Ocean') || biome.includes('Sea')) ? biome : (isRiver ? 'River' : (isLake ? 'Lake' : 'None')),
            nationId,
            city,
            poi,
            isRiver,
            isLake,
            travelSpeed,
            difficultyValue,
            forageRating,
            foragePct,
            localMinorFaction,
            get details() {
                return getProceduralHooks(x, y, biome, localMinorFaction, city, poi, temp, h, selfSeed);
            }
        };
    }

    _isLand(s) {
        return s && s.height >= 0.49 && !['Deep Ocean','Ocean','Shallow Sea'].includes(s.biome);
    }

    // ── Main Generation Pipeline ─────────────────────────────────────────────
    generate() {
        const noiseA = new GradientNoise2D(new RNG(this.seed + '_A'));
        const noiseB = new GradientNoise2D(new RNG(this.seed + '_B'));
        const noiseM = new GradientNoise2D(new RNG(this.seed + '_M'));
        const noiseT = new GradientNoise2D(new RNG(this.seed + '_T'));

        const W = this.width, H = this.height;

        // ── 1. Heightmap generation with Ridged Multifractals ────────────────
        const rawH = new Float32Array(W * H);
        let hMin = Infinity, hMax = -Infinity;

        // Pre-generate Volcanic Arc Subduction Fault Chains for 'islands' landmass
        const islandHotspots = [];
        if (this.landmassType === 'islands') {
            const arcCount = 5;
            const arcRng = new RNG(this.seed + '_arcs');
            for (let a = 0; a < arcCount; a++) {
                const x0 = arcRng.range(W * 0.1, W * 0.9);
                const y0 = arcRng.range(H * 0.1, H * 0.9);
                const angle = arcRng.range(0, Math.PI * 2);
                const length = arcRng.range(W * 0.25, W * 0.55);
                const curvature = arcRng.range(-0.4, 0.4);

                const numSpots = arcRng.int(5, 10);
                for (let s = 0; s < numSpots; s++) {
                    const t = s / (numSpots - 1);
                    const curveOffset = Math.sin(t * Math.PI) * length * curvature;
                    const hx = x0 + Math.cos(angle) * (t * length) - Math.sin(angle) * curveOffset;
                    const hy = y0 + Math.sin(angle) * (t * length) + Math.cos(angle) * curveOffset;
                    const radius = arcRng.range(W * 0.025, W * 0.065);
                    const peak = arcRng.range(0.6, 1.0);
                    islandHotspots.push({ x: hx, y: hy, radius, peak, isMajor: s % 3 === 0 });
                }
            }
        }

        for (let y = 0; y < H; y++) {
            for (let x = 0; x < W; x++) {
                const idx = y * W + x;
                let nx = (x / W) * 3.2;
                let ny = (y / H) * 1.6;

                let baseH = noiseA.doubleWarpedFbm(nx, ny, 6);
                let ridgeH = noiseB.ridgedFbm(nx * 2.2, ny * 2.2, 5);

                // Blend base continent warping with sharp tectonic ridged multifractals
                let h = baseH * 0.65 + ridgeH * 0.35;

                // Landmass Shape Masks
                if (this.landmassType === 'pangea') {
                    const dx = (x / W - 0.5) * 2;
                    const dy = (y / H - 0.5) * 2;
                    const dist = Math.sqrt(dx * dx + dy * dy);
                    h -= dist * dist * 0.38;
                } else if (this.landmassType === 'islands') {
                    // ── Advanced Volcanic Arc & Coral Atoll Archipelago Engine ──
                    let arcElevation = 0;
                    let coralAtollRing = 0;

                    for (const spot of islandHotspots) {
                        const dx = Math.abs(x - spot.x);
                        const wrappedDx = Math.min(dx, W - dx); // Wrap longitude
                        const dy = y - spot.y;
                        const dist = Math.sqrt(wrappedDx * wrappedDx + dy * dy);

                        if (dist < spot.radius * 2.5) {
                            // Volcanic island central peak
                            const normDist = dist / spot.radius;
                            const peakInfluence = spot.peak * Math.exp(-normDist * normDist * 1.8);
                            arcElevation = Math.max(arcElevation, peakInfluence);

                            // Coral Barrier Reef Atoll Ring surrounding main volcanic hubs
                            if (spot.isMajor && normDist > 1.1 && normDist < 1.6) {
                                coralAtollRing = Math.max(coralAtollRing, 0.42 * (1 - Math.abs(normDist - 1.35) / 0.25));
                            }
                        }
                    }

                    // High-frequency fractal shoreline erosion noise
                    const shoreErosion = noiseA.fbm(x / W * 18, y / H * 18, 4) * 0.18;
                    const microIslets = noiseB.cellularVoronoi(x / W * 16, y / H * 16);
                    const isletFactor = (microIslets.edge < 0.12) ? 0.25 : 0;

                    // Combine volcanic arc hotspots, atolls, islets, and jagged shore erosion
                    h = arcElevation * 0.70 + coralAtollRing * 0.20 + isletFactor - shoreErosion - 0.12;
                } else {
                    const latFrac = Math.abs((y / H) - 0.5) * 2;
                    h -= latFrac * latFrac * 0.16;
                }

                rawH[idx] = h;
                if (h < hMin) hMin = h;
                if (h > hMax) hMax = h;
            }
        }

        // Normalize height map
        const hRange = hMax - hMin;
        for (let i = 0; i < W * H; i++) {
            this.heightMap[i] = (rawH[i] - hMin) / hRange;
        }

        // Quantile-based Sea Level: guarantees around 60% water coverage on any seed
        let targetWaterFrac = 0.60; // 60% water
        if (this.landmassType === 'islands') targetWaterFrac = 0.68;
        if (this.landmassType === 'pangea')  targetWaterFrac = 0.53;

        // Sample quantile from sorted heightmap array
        const sampleSize = Math.min(20000, W * H);
        const samples = new Float32Array(sampleSize);
        const step = Math.floor((W * H) / sampleSize);
        for (let s = 0; s < sampleSize; s++) {
            samples[s] = this.heightMap[s * step];
        }
        samples.sort();
        this.seaLevel = samples[Math.floor(sampleSize * targetWaterFrac)];

        // Active Tectonics: Sharpen mountains & deepen ocean trenches
        if (this.tectonics === 'active') {
            for (let i = 0; i < W * H; i++) {
                const h = this.heightMap[i];
                if (h > 0.54) this.heightMap[i] = Math.min(1, 0.54 + Math.pow(h - 0.54, 0.85) * 1.6);
                if (h < 0.38) this.heightMap[i] = Math.max(0, 0.38 - Math.pow(0.38 - h, 0.85) * 1.4);
            }
        }

        // ── 2. Climate & Orographic Wind Vector Thermodynamics ───────────────
        const climateOffset = { balanced: 0, frozen: -15, desolate: 12, volcanic: 22 };
        const moistureScale = { balanced: 1, frozen: 0.5, desolate: 0.3, volcanic: 0.65 };
        const dT = climateOffset[this.climate] || 0;
        const dM = moistureScale[this.climate] || 1;

        // Base Temperature & Unmodified Moisture
        for (let y = 0; y < H; y++) {
            for (let x = 0; x < W; x++) {
                const idx = y * W + x;
                const h = this.heightMap[idx];
                const latDeg = ((H / 2 - y) / (H / 2)) * 90;
                const latNoise = noiseT.fbm(x / W * 2.8, y / H * 2.8, 3) * 8.5;
                const latAbs = Math.max(0, Math.min(90, Math.abs(latDeg + latNoise)));

                const altCool = h > 0.5 ? (h - 0.5) * 64 : 0;
                const baseTemp = 32 - latAbs * 0.78 + dT - altCool;
                this.tempMap[idx] = Math.round(baseTemp);

                const rawMoist = (noiseM.fbm(x / W * 5.2, y / H * 5.2, 4) + 1) / 2;
                const hadley = Math.sin((latAbs / 90) * Math.PI * 3) * 0.18;
                let moisture = Math.max(0, Math.min(1, rawMoist + hadley)) * dM;
                if (h < 0.49) moisture = Math.max(moisture, 0.85); // High humidity over ocean
                this.moistureMap[idx] = Math.round(moisture * 100);
            }
        }

        // Orographic Wind Vector Advection (Rain Shadow Effect)
        // Advect moisture according to latitude Trade Winds & Westerlies
        for (let y = 0; y < H; y++) {
            const latDeg = Math.abs(((H / 2 - y) / (H / 2)) * 90);
            // Wind direction: Easterlies (-1) in tropics & poles, Westerlies (+1) in mid-latitudes
            const windDirX = (latDeg > 30 && latDeg < 60) ? 1 : -1;
            
            let carriedMoisture = 0.5;
            for (let step = 0; step < W; step++) {
                const x = (windDirX === 1) ? (step % W) : ((W - 1 - step + W) % W);
                const idx = y * W + x;
                const h = this.heightMap[idx];

                if (h < this.seaLevel) {
                    // Pick up ocean moisture
                    carriedMoisture = Math.min(1.0, carriedMoisture + 0.08);
                } else {
                    // Over land: check elevation climb
                    const prevX = (x - windDirX + W) % W;
                    const prevH = this.heightMap[y * W + prevX];
                    const deltaH = h - prevH;

                    if (deltaH > 0.02) {
                        // Climbing mountain slope: dump rain on windward slope
                        const rainDump = deltaH * 2.5 * carriedMoisture;
                        this.moistureMap[idx] = Math.min(100, Math.round(this.moistureMap[idx] + rainDump * 100));
                        carriedMoisture = Math.max(0.05, carriedMoisture - rainDump);
                    } else if (deltaH < -0.02 || h > 0.68) {
                        // Descending mountain back or high plateau: dry rain shadow!
                        carriedMoisture *= 0.75;
                        this.moistureMap[idx] = Math.max(2, Math.round(this.moistureMap[idx] * 0.45));
                    }
                }
            }
        }

        // Aquifer & Magma Maps
        for (let idx = 0; idx < W * H; idx++) {
            const h = this.heightMap[idx];
            const m = this.moistureMap[idx] / 100;
            this.aquiferMap[idx] = Math.max(5, Math.floor(m * 180 - (h > 0.65 ? 50 : 0)));
            this.magmaMap[idx] = Math.round(h * 60 + (this.climate === 'volcanic' ? 35 : 0));
        }

        // ── 4. Biome Classification ──────────────────────────────────────────
        this._classifyBiomes();

        // ── 5. Hydrology ─────────────────────────────────────────────────────
        this._runHydrology();

        // ── 6. Politics ──────────────────────────────────────────────────────
        this._buildPolitics();

        // ── 7. Points of Interest ────────────────────────────────────────────
        this._scatterPOIs();
    }

    _classifyBiomes() {
        const W = this.width, H = this.height;
        const noiseAnom = new GradientNoise2D(new RNG(this.seed + '_Anom'));

        this.anomalyEpicenters = [];
        if (this.allowMagic) {
            const numEpicenters = this.rng.int(1, 3);
            const anomalyTypes = ['Astral Rift', 'Mana Wastes', 'Fey Wildwood', 'Obsidian Spireland', 'Crystal Fields', 'Bioluminescent Jungle'];
            
            const landCoords = [];
            for (let ly = 0; ly < H; ly++) {
                for (let lx = 0; lx < W; lx++) {
                    if (this.heightMap[ly * W + lx] >= this.seaLevel) {
                        landCoords.push({ x: lx, y: ly });
                    }
                }
            }

            if (landCoords.length > 0) {
                for (let e = 0; e < numEpicenters; e++) {
                    const pickedLand = this.rng.pick(landCoords);
                    const radius = Math.max(6, Math.floor(Math.min(W, H) * (0.07 + this.rng.next() * 0.04)));
                    const aType = this.rng.pick(anomalyTypes);
                    this.anomalyEpicenters.push({ x: pickedLand.x, y: pickedLand.y, radius, type: aType });
                }
            }
        }

        for (let y = 0; y < H; y++) {
            for (let x = 0; x < W; x++) {
                const idx = y * W + x;
                const h = this.heightMap[idx];
                const temp = this.tempMap[idx];
                const m = this.moistureMap[idx];
                const aquifer = this.aquiferMap[idx];
                let biome = 'Ocean';

                // ── Ocean / Sea Depth Gradients ──
                if (h < this.seaLevel - 0.26) {
                    biome = h < this.seaLevel - 0.36 ? 'Trench' : 'Deep Ocean';
                } else if (h < this.seaLevel - 0.07) {
                    biome = 'Ocean';
                } else if (h < this.seaLevel) {
                    if (temp > 22) biome = 'Coral Reef';
                    else if (temp < 14) biome = 'Kelp Forest';
                    else biome = 'Shallow Sea';
                } else {
                    // ── Land ──
                    let isAnomaly = false;
                    if (this.anomalyEpicenters && this.anomalyEpicenters.length > 0) {
                        for (const epicenter of this.anomalyEpicenters) {
                            const dx = Math.abs(x - epicenter.x);
                            const wrappedDx = Math.min(dx, W - dx);
                            const dy = y - epicenter.y;
                            const dist = Math.sqrt(wrappedDx * wrappedDx + dy * dy);

                            const edgeNoise = noiseAnom.fbm(x / W * 10, y / H * 10, 2) * epicenter.radius * 0.4;
                            if (dist < epicenter.radius + edgeNoise) {
                                isAnomaly = true;
                                biome = epicenter.type;
                                break;
                            }
                        }
                    }

                    if (!isAnomaly) {
                        if (temp < -15) {
                            biome = (h > 0.7) ? 'Glacier' : 'Ice Cap';
                        } else if (temp < -5) {
                            biome = (m > 40) ? 'Tundra' : 'Alpine Meadow';
                        } else if (h > 0.85) {
                            biome = (this.climate === 'volcanic' || temp > 20) ? 'Lava Field' : 'Snowcap';
                        } else if (h > 0.76) {
                            biome = (temp < 0) ? 'Snowcap' : 'Mountain';
                        } else if (h > 0.62) {
                            biome = (m < 20) ? 'Canyon' : 'Highland';
                        } else if (h > 0.57) {
                            biome = (m < 15) ? 'Mesa' : 'Plateau';
                        } else {
                            if (temp > 24) {
                                if (m < 15) biome = m < 8 ? 'Dune Sea' : 'Desert';
                                else if (m < 35) biome = 'Savanna';
                                else if (m > 75) biome = 'Rainforest';
                                else biome = 'Shrubland';
                            } else if (temp > 10) {
                                if (m < 12) biome = 'Desert';
                                else if (m < 30) biome = 'Grassland';
                                else if (m > 70) biome = 'Temperate Rainforest';
                                else if (m > 50) biome = 'Forest';
                                else biome = 'Shrubland';
                            } else {
                                if (m < 15) biome = 'Steppe';
                                else if (m > 65) biome = 'Taiga';
                                else if (m > 45) biome = 'Forest';
                                else biome = 'Grassland';
                            }
                        }

                        if (biome === 'Forest' || biome === 'Grassland' || biome === 'Shrubland') {
                            if (h < 0.52 && m > 65) {
                                biome = (temp > 16) ? 'Swamp' : 'Mangrove Swamp';
                            }
                        }

                        if ((biome === 'Desert' || biome === 'Dune Sea') && aquifer > 115) {
                            biome = 'Oasis';
                        }
                    }
                }

                this.biomeMap[idx] = BIOME_KEYS.indexOf(biome) !== -1 ? BIOME_KEYS.indexOf(biome) : 1;
            }
        }
    }

    _fillDepressionAndFindSpillover(startX, startY, W, H, dirs) {
        const visitedBasin = new Set();
        const queue = [{ x: startX, y: startY }];
        const basin = [];
        const rim = [];
        
        const startIdx = startY * W + startX;
        visitedBasin.add(startIdx);
        
        const maxBasinSize = Math.min(150, Math.floor(W * 0.12));

        while (queue.length > 0 && basin.length < maxBasinSize) {
            const curr = queue.shift();
            basin.push(curr);
            const currIdx = curr.y * W + curr.x;
            const currH = this.heightMap[currIdx];

            for (const [dx, dy] of dirs) {
                const nx = (curr.x + dx + W) % W;
                const ny = Math.max(0, Math.min(H - 1, curr.y + dy));
                const nIdx = ny * W + nx;

                if (!visitedBasin.has(nIdx)) {
                    const nH = this.heightMap[nIdx];
                    if (nH <= currH + 0.04) {
                        visitedBasin.add(nIdx);
                        queue.push({ x: nx, y: ny });
                    } else {
                        rim.push({ x: nx, y: ny, h: nH });
                    }
                }
            }
        }

        if (rim.length === 0) return null;

        rim.sort((a, b) => a.h - b.h);
        const spill = rim[0];
        const spillH = spill.h;

        const lakeBiomeName = spillH > 0.72 ? 'Alpine Lake' : (spillH > 0.60 ? 'Crater Lake' : 'Lake');
        let lakeBiomeIdx = BIOME_KEYS.indexOf(lakeBiomeName);
        if (lakeBiomeIdx === -1) lakeBiomeIdx = BIOME_KEYS.indexOf('Lake');

        for (const bCell of basin) {
            const bIdx = bCell.y * W + bCell.x;
            if (this.heightMap[bIdx] <= spillH + 0.01 && this.heightMap[bIdx] >= 0.48) {
                this.lakeMap[bIdx] = 1;
                if (lakeBiomeIdx !== -1) {
                    this.biomeMap[bIdx] = lakeBiomeIdx;
                }
            }
        }

        return spill;
    }

    _runHydrology() {
        const W = this.width, H = this.height;
        const dirs = [
            [0,1],[1,0],[0,-1],[-1,0],
            [1,1],[1,-1],[-1,1],[-1,-1]
        ];

        // 1. Gather potential high-mountain peaks/sources
        const sources = [];
        for (let y = 0; y < H; y++) {
            for (let x = 0; x < W; x++) {
                const idx = y * W + x;
                const h = this.heightMap[idx];
                const biome = BIOME_KEYS[this.biomeMap[idx]];
                if (h >= 0.72 || biome === 'Mountain' || biome === 'Snowcap' || biome === 'Volcano') {
                    sources.push({ x, y });
                }
            }
        }

        if (sources.length < 50) {
            for (let y = 0; y < H; y++) {
                for (let x = 0; x < W; x++) {
                    const idx = y * W + x;
                    if (this.heightMap[idx] >= 0.60) {
                        sources.push({ x, y });
                    }
                }
            }
        }

        if (sources.length === 0) return;

        // 2. Generate rivers using downhill spillway carving & lake depression spillover
        const numRivers = Math.floor(W * 0.16);
        for (let i = 0; i < numRivers; i++) {
            let start = this.rng.pick(sources);
            let attempts = 0;
            while (attempts < 20 && this.riverMap[start.y * W + start.x] === 1) {
                start = this.rng.pick(sources);
                attempts++;
            }

            let rx = start.x, ry = start.y;
            let steps = 0;
            const pathPoints = [];
            const visited = new Uint8Array(W * H);
            const maxSteps = Math.max(400, W);

            while (steps < maxSteps) {
                const sIdx = ry * W + rx;
                if (visited[sIdx]) break;
                visited[sIdx] = 1;
                
                pathPoints.push({ x: rx, y: ry });
                this.riverMap[sIdx] = 1;

                const curH = this.heightMap[sIdx];
                const curBiome = BIOME_KEYS[this.biomeMap[sIdx]];

                // Stop when we reach sea, ocean, or existing river
                if (curH < 0.49 || curBiome.includes('Ocean') || curBiome.includes('Sea') || (steps > 5 && (this.riverMap[sIdx] === 1 || this.lakeMap[sIdx] === 1))) {
                    break;
                }

                // Check downhill neighbors
                let best = null, bestH = curH;

                for (const [dx, dy] of dirs) {
                    const nx = (rx + dx + W) % W;
                    const ny = Math.max(0, Math.min(H - 1, ry + dy));
                    const nIdx = ny * W + nx;
                    
                    if (visited[nIdx]) continue;
                    
                    const nH = this.heightMap[nIdx];
                    if (nH < curH && nH < bestH) {
                        bestH = nH;
                        best = [nx, ny];
                    }
                }

                if (best) {
                    [rx, ry] = best;
                } else {
                    // Reached a depression minimum! Form a lake and spill over rim
                    const spill = this._fillDepressionAndFindSpillover(rx, ry, W, H, dirs);
                    if (spill && !visited[spill.y * W + spill.x]) {
                        pathPoints.push({ x: spill.x, y: spill.y });
                        rx = spill.x;
                        ry = spill.y;
                    } else {
                        break;
                    }
                }
                steps++;
            }

            if (pathPoints.length >= 2) {
                this.riverPaths.push(pathPoints);
            }
        }
    }

    _buildPolitics() {
        const W = this.width, H = this.height;
        const dirs = [[0,1],[1,0],[0,-1],[-1,0]];
        const numNations = this.rng.int(5, 9);
        const palettes = [
            '#66bb66','#6699cc','#e07a5f','#f2cc8f','#95d5b2',
            '#c77dff','#f4a261','#48cae4','#e63946','#2dc653',
        ];
        this.rng.shuffle(palettes);

        this.nations = [];
        this.citiesMap.clear();

        const styles = ['elven', 'dwarven', 'norse', 'roman', 'gothic', 'eldritch'];
        for (let i = 0; i < numNations; i++) {
            const style = styles[i % styles.length];
            const capName = this.nameGen.generate(style, 'city');
            const natName = this.nameGen.generate(style, 'nation');
            this.nations.push({
                name: natName,
                color: palettes[i % palettes.length],
                capital: capName,
                id: i,
                style: style
            });
        }

        const queue = [];
        for (let i = 0; i < numNations; i++) {
            let cx = 0, cy = 0, found = false;
            for (let att = 0; att < 500; att++) {
                cx = this.rng.int(0, W - 1);
                cy = this.rng.int(0, H - 1);
                const idx = cy * W + cx;
                const h = this.heightMap[idx];
                const sBiome = BIOME_KEYS[this.biomeMap[idx]];

                if (h < 0.49 || ['Deep Ocean','Ocean','Shallow Sea','Mountain','Snowcap','Glacier','Volcano','Lava Field','Obsidian Spireland'].includes(sBiome)) continue;
                if (this.nationMap[idx] !== -1) continue;

                let nearWater = false;
                for (const [dx, dy] of dirs) {
                    const nx = (cx + dx + W) % W;
                    const ny = Math.max(0, Math.min(H - 1, cy + dy));
                    const nIdx = ny * W + nx;
                    if (this.heightMap[nIdx] < 0.49 || this.riverMap[nIdx] === 1) nearWater = true;
                }

                if (nearWater || att > 300) { found = true; break; }
            }

            const idx = cy * W + cx;
            this.nationMap[idx] = i;
            const pop = this.rng.int(30000, 500000);
            
            const citySeed = this.rng.int(1, 2000000000).toString();
            const citySize = pop > 200000 ? 'metropolis' : (pop > 80000 ? 'large' : 'medium');
            const cityStyle = this.nations[i].style;
            
            const cityObj = { name: this.nations[i].capital, isCapital: true, nationId: i, pop, seed: citySeed, size: citySize, style: cityStyle };
            this.citiesMap.set(`${cx},${cy}`, cityObj);
            this.cities.push({ name: this.nations[i].capital, x: cx, y: cy, nationId: i, isCapital: true, pop, seed: citySeed, size: citySize, style: cityStyle });
            queue.push({ x: cx, y: cy, nationId: i, cost: 0 });
        }

        while (queue.length > 0) {
            const curr = queue.shift();
            for (const [dx, dy] of dirs) {
                const nx = (curr.x + dx + W) % W;
                const ny = Math.max(0, Math.min(H - 1, curr.y + dy));
                const idx = ny * W + nx;
                const h = this.heightMap[idx];

                if (h < 0.49 || this.nationMap[idx] !== -1) continue;

                const cost = curr.cost + 1 + (h > 0.72 ? 8 : 0) + (this.riverMap[idx] ? 0.5 : 0);
                this.nationMap[idx] = curr.nationId;
                
                binaryInsert(queue, { x: nx, y: ny, nationId: curr.nationId, cost });
            }
        }

        const numTowns = Math.floor(W * 0.15);
        for (let i = 0; i < numTowns; i++) {
            const cx = this.rng.int(0, W - 1);
            const cy = this.rng.int(0, H - 1);
            const idx = cy * W + cx;
            const h = this.heightMap[idx];
            const sBiome = BIOME_KEYS[this.biomeMap[idx]];

            if (h < 0.49 || this.citiesMap.has(`${cx},${cy}`) || ['Mountain','Snowcap','Glacier','Volcano','Lava Field','Obsidian Spireland'].includes(sBiome)) continue;

            const nationId = this.nationMap[idx];
            const style = (nationId !== -1 && this.nations[nationId]) ? this.nations[nationId].style : this.rng.pick(['elven', 'dwarven', 'norse', 'roman', 'gothic']);
            const name = this.nameGen.generate(style, 'city');
            const isCity = this.rng.next() < 0.4;
            const pop = isCity ? this.rng.int(10000, 80000) : this.rng.int(200, 3000);
            
            const citySeed = this.rng.int(1, 2000000000).toString();
            const citySize = pop > 50000 ? 'large' : (pop > 10000 ? 'medium' : 'small');
            
            const cityObj = { name, isCapital: false, nationId: this.nationMap[idx], pop, seed: citySeed, size: citySize, style };
            this.citiesMap.set(`${cx},${cy}`, cityObj);
            this.cities.push({ name, x: cx, y: cy, nationId: this.nationMap[idx], isCapital: false, pop, seed: citySeed, size: citySize, style });
        }
    }

    _scatterPOIs() {
        const W = this.width, H = this.height;
        const numPOIs = Math.floor(W * 0.08);
        this.pois = [];
        this.poisMap.clear();

        for (let i = 0; i < numPOIs; i++) {
            let px = 0, py = 0, idx = 0, h = 0, sBiome = '', att = 0;
            while (att < 200) {
                px = this.rng.int(0, W - 1);
                py = this.rng.int(0, H - 1);
                idx = py * W + px;
                h = this.heightMap[idx];
                sBiome = BIOME_KEYS[this.biomeMap[idx]];
                if (h >= 0.49 && !this.citiesMap.has(`${px},${py}`) && !this.poisMap.has(`${px},${py}`)) break;
                att++;
            }

            if (h < 0.49) continue;

            const candidates = POI_TYPES.filter(p => p.biomes.includes(sBiome));
            const poiType = candidates.length > 0 ? this.rng.pick(candidates) : this.rng.pick(POI_TYPES);
            const poiName = poiType.icon + ' ' + poiType.name;

            let minorFaction = "None";
            if (this.rng.next() < 0.4) {
                minorFaction = this.nameGen.factionName();
            }

            const poiSeed = `world_${this.seed}_${px}_${py}`;
            const proceduralDesc = generatePoiDescription(poiType.id, poiSeed, poiName);

            const poiObj = {
                type:  poiType.id,
                icon:  poiType.icon,
                label: poiType.name,
                name:  poiName,
                desc:  proceduralDesc,
                theme: poiType.theme,
                seed:  poiSeed,
                minorFaction
            };

            this.poisMap.set(`${px},${py}`, poiObj);
            this.pois.push({ ...poiObj, x: px, y: py });
        }
    }
}
