import { RNG, GradientNoise2D, NameGen, binaryInsert } from './utils.js';
import { BIOME_KEYS, BIOMES, POI_TYPES, getProceduralHooks } from './biomes.js';
import { generatePoiDescription } from './descriptionGenerator.js';

export class WorldEngine {
    constructor(seed, sizeMode, coreType, tectonics, atmosphere, climate, customW = 512, customH = 256, allowMagic = true, landmassType = 'continents') {
        this.seed       = seed;
        this.rng        = new RNG(seed);
        this.sizeMode   = sizeMode;
        this.coreType   = coreType;
        this.tectonics  = tectonics;
        this.atmosphere = atmosphere;
        this.climate    = climate;
        this.allowMagic = allowMagic;
        this.landmassType = landmassType;

        let W = 256;
        if (sizeMode === 'small') W = 128;
        else if (sizeMode === 'medium') W = 256;
        else if (sizeMode === 'large') W = 512;
        else if (sizeMode === 'legendary') W = 1024;
        else if (sizeMode === 'epic') W = 2048;
        else if (sizeMode === 'custom') W = parseInt(customW, 10) || 512;

        this.width  = W;
        this.height = sizeMode === 'custom' ? (parseInt(customH, 10) || 256) : Math.floor(W * 0.5);

        this.nameGen = new NameGen(new RNG(seed + '_names'));
        this.nations = [];
        this.cities  = [];
        this.pois    = [];

        this.citiesMap = new Map();
        this.poisMap = new Map();

        // Flat TypedArrays for low-memory overhead (crucial for 2048x1024 grids)
        const size = this.width * this.height;
        this.heightMap   = new Float32Array(size);
        this.tempMap     = new Int8Array(size);
        this.moistureMap = new Uint8Array(size);
        this.aquiferMap  = new Uint8Array(size);
        this.magmaMap    = new Uint8Array(size);
        this.biomeMap    = new Uint8Array(size);
        this.nationMap   = new Int16Array(size);
        this.riverMap    = new Uint8Array(size);
        this.lakeMap     = new Uint8Array(size);

        // Fill initial nation map
        this.nationMap.fill(-1);

        // Transparent Grid Proxy: allows world.grid[y][x] to return virtual sector objects lazily
        this.grid = new Proxy([], {
            get: (target, yStr) => {
                const y = parseInt(yStr, 10);
                if (isNaN(y) || y < 0 || y >= this.height) return target[yStr];
                return new Proxy([], {
                    get: (rowTarget, xStr) => {
                        const x = parseInt(xStr, 10);
                        if (isNaN(x) || x < 0 || x >= this.width) return rowTarget[xStr];
                        return this.getSector(x, y);
                    }
                });
            }
        });

        this.atmosphereLayers = [
            { name:'Troposphere',   alt:'0–12 km',        desc:'The weather layer. Contains 75% of atmospheric mass. All weather phenomena occur here.',             temp:'+15°C to −57°C',  pressure:'1.0–0.1 atm' },
            { name:'Stratosphere',  alt:'12–50 km',       desc:'Dry and stable. The ozone layer shields the surface from ultraviolet radiation.',                   temp:'−57°C to −3°C',   pressure:'0.1–0.001 atm' },
            { name:'Mesosphere',    alt:'50–85 km',       desc:'The coldest atmospheric layer. Incoming meteors incandesce and burn up here.',                      temp:'−3°C to −90°C',   pressure:'0.001–0.00001 atm' },
            { name:'Thermosphere',  alt:'85–600 km',      desc:'Ionosphere sub-layer. Solar radiation excites gas particles, creating polar auroras.',              temp:'−90°C to +2500°C',pressure:'Trace' },
            { name:'Exosphere',     alt:'600–10,000 km',  desc:'The outermost atmospheric boundary. Gas molecules escape into interplanetary space here.',          temp:'2500°C (molecular)',pressure:'Near-vacuum' },
            { name:'Magnetosphere', alt:'10,000–60,000 km',desc:'Magnetic field generated by the planetary core. Deflects solar wind and cosmic radiation.',       temp:'Stellar ambient', pressure:'Vacuum' },
        ];

        this.coreLayers = [
            { name:'Crust',          thickness:'5–70 km',        composition:'Silicate rocks (Basalt, Granite, Andesite)',                      state:'Solid',                    temp:'Surface to 900°C' },
            { name:'Lithosphere',    thickness:'80–150 km',      composition:'Brittle crust and rigid upper mantle fused together',              state:'Rigid Solid',              temp:'900–1,200°C' },
            { name:'Asthenosphere',  thickness:'180–250 km',     composition:'Partially molten ductile silicate rock enabling plate motion',     state:'Plastic / Semi-fluid',     temp:'1,200–1,400°C' },
            { name:'Mantle',         thickness:'2,890 km',       composition:'Magnesium-iron silicates (Peridotite, Pyroxenite)',                state:'Viscous Solid / Convecting',temp:'1,400–3,700°C' },
            { name:'Outer Core',     thickness:'2,200 km',       composition:this._coreCompositionName() + ' (liquid)',                          state:'Molten Liquid (Dynamo)',   temp:'3,700–5,000°C' },
            { name:'Inner Core',     thickness:'1,280 km radius',composition:this._coreCompositionName() + ' (crystalline)',                     state:'Crystalline Solid',        temp:'5,000–6,000°C' },
        ];

        this.generate();
    }

    _coreCompositionName() {
        const m = { 'iron-nickel':'Iron-Nickel Alloy', 'silicate':'Silicate Oxide Matrix',
                    'gold-molten':'Molten Heavy Metals (Au, Pt, U)', 'crystal':'Volatile Energy Crystal' };
        return m[this.coreType] || 'Iron-Nickel Alloy';
    }

    getSector(x, y) {
        const idx = y * this.width + x;
        if (idx < 0 || idx >= this.width * this.height) return null;

        const h = this.heightMap[idx];
        const temp = this.tempMap[idx];
        const moisture = this.moistureMap[idx];
        const aquifer = this.aquiferMap[idx];
        const magmaPct = this.magmaMap[idx];
        const biomeIndex = this.biomeMap[idx];
        const biome = BIOME_KEYS[biomeIndex] || 'Ocean';
        const nationId = this.nationMap[idx];
        const isRiver = this.riverMap[idx] === 1;
        const isLake = this.lakeMap[idx] === 1;

        const latDeg = ((this.height / 2 - y) / (this.height / 2)) * 90;
        const lonDeg = ((x / this.width) - 0.5) * 360;

        const coordKey = `${x},${y}`;
        const city = this.citiesMap.get(coordKey) || null;
        const poi = this.poisMap.get(coordKey) || null;

        // Travel difficulty scale
        let travelSpeed = "Normal Travel (1x)";
        let difficultyValue = 1;
        if (h > 0.82) { travelSpeed = "Impassable Peaks (6x)"; difficultyValue = 8; }
        else if (h > 0.72) { travelSpeed = "Challenging Climb (4x)"; difficultyValue = 6; }
        else if (biome.includes('Ocean') || biome.includes('Sea')) { travelSpeed = "Requires Vessel"; difficultyValue = 9; }
        else if (biome === 'Swamp' || biome === 'Mangrove Swamp' || biome === 'Dune Sea' || biome === 'Obsidian Spireland' || biome === 'Badlands') { travelSpeed = "Difficult Terrain (2x)"; difficultyValue = 4; }
        else if (biome === 'Glacier' || biome === 'Ice Cap') { travelSpeed = "Treacherous Ice (3x)"; difficultyValue = 5; }

        // Survival / Forage probability
        let forageRating = "Moderate (50% chance/day)";
        let foragePct = 50;
        if (biome.includes('Ocean') || biome.includes('Sea')) { forageRating = "Fishing Abundant (80%)"; foragePct = 80; }
        else if (biome === 'Desert' || biome === 'Dune Sea' || biome === 'Ash Wastes' || biome === 'Glacier' || biome === 'Ice Cap' || biome === 'Mana Wastes' || biome === 'Obsidian Spireland' || biome === 'Astral Rift') { forageRating = "Barren Wasteland (0%)"; foragePct = 0; }
        else if (biome === 'Forest' || biome === 'Temperate Rainforest' || biome === 'Fey Wildwood' || biome === 'Bioluminescent Jungle' || biome === 'Oasis') { forageRating = "Sustiful / Rich (90%)"; foragePct = 90; }
        else if (biome === 'Grassland' || biome === 'Alpine Meadow' || biome === 'Valley') { forageRating = "Good Foraging (75%)"; foragePct = 75; }

        // Seeded local minor faction
        let localMinorFaction = "None";
        if (poi && poi.minorFaction) {
            localMinorFaction = poi.minorFaction;
        } else {
            const factionRng = new RNG(this.seed + `_cell_fac_${x}_${y}`);
            if (factionRng.next() < 0.22) {
                const groups = [
                    "The Emerald Druids", "Red Fang Goblin Clan", "Shadow Syndicate",
                    "Aurelian Hermits", "Iron Pick Miner Guild", "Deepwood Rangers", "The Broken Shield Outlaws",
                    "Spell-Warped Cultists", "Crystalline Sentinels", "Fey Court Outriders", "Ghost-light Wanderers"
                ];
                localMinorFaction = factionRng.pick(groups);
            }
        }

        const info = BIOMES[biome] || BIOMES['Ocean'];
        const selfSeed = this.seed;

        return {
            x, y,
            lat: latDeg.toFixed(1),
            lon: lonDeg.toFixed(1),
            height: h,
            temp,
            moisture,
            aquifer,
            magmaPct,
            biome,
            soil: info.soil,
            bedrock: info.bedrock,
            liquid: (biome.includes('Ocean') || biome.includes('Sea')) ? biome : (isRiver ? 'River' : (isLake ? 'Lake' : 'None')),
            nationId,
            city,
            poi,
            isRiver,
            isLake,
            travelSpeed,
            difficultyValue,
            forageRating,
            foragePct,
            localMinorFaction,
            get details() {
                return getProceduralHooks(x, y, biome, localMinorFaction, city, poi, temp, h, selfSeed);
            }
        };
    }

    _isLand(s) {
        return s && s.height >= 0.49 && !['Deep Ocean','Ocean','Shallow Sea'].includes(s.biome);
    }

    // ── Main Generation Pipeline ─────────────────────────────────────────────
    generate() {
        const noiseA = new GradientNoise2D(new RNG(this.seed + '_A'));
        const noiseB = new GradientNoise2D(new RNG(this.seed + '_B'));
        const noiseM = new GradientNoise2D(new RNG(this.seed + '_M'));
        const noiseT = new GradientNoise2D(new RNG(this.seed + '_T'));

        const W = this.width, H = this.height;

        // ── 1. Heightmap generation with landmass masks ──────────────────────
        const rawH = new Float32Array(W * H);
        let hMin = Infinity, hMax = -Infinity;

        for (let y = 0; y < H; y++) {
            for (let x = 0; x < W; x++) {
                const idx = y * W + x;
                let nx = x / W * 3;
                let ny = y / H * 1.5;

                // Adjust frequency if islands
                if (this.landmassType === 'islands') {
                    nx = x / W * 8.5;
                    ny = y / H * 4.2;
                }

                let h = noiseA.warpedFbm(nx, ny, 6);

                // Landmass Shape Masks
                if (this.landmassType === 'pangea') {
                    const dx = (x / W - 0.5) * 2;
                    const dy = (y / H - 0.5) * 2;
                    const dist = Math.sqrt(dx * dx + dy * dy);
                    h -= dist * dist * 0.35; // pull edges down
                } else if (this.landmassType === 'islands') {
                    h -= 0.14; // submerge lowlands, creating chains
                } else {
                    // standard continents: push poles slightly towards water/ice caps
                    const latFrac = Math.abs((y / H) - 0.5) * 2;
                    h -= latFrac * latFrac * 0.15;
                }

                rawH[idx] = h;
                if (h < hMin) hMin = h;
                if (h > hMax) hMax = h;
            }
        }

        // Normalize height
        const hRange = hMax - hMin;
        for (let i = 0; i < W * H; i++) {
            this.heightMap[i] = (rawH[i] - hMin) / hRange;
        }

        // Tectonics
        if (this.tectonics === 'active') {
            for (let i = 0; i < W * H; i++) {
                const h = this.heightMap[i];
                if (h > 0.55) this.heightMap[i] = Math.min(1, 0.55 + (h - 0.55) * 1.8);
                if (h < 0.4)  this.heightMap[i] = Math.max(0, 0.4 - (0.4 - h) * 1.6);
            }
        }

        // ── 2. Climate offsets ───────────────────────────────────────────────
        const climateOffset = { balanced: 0, frozen: -15, desolate: 12, volcanic: 22 };
        const moistureScale = { balanced: 1, frozen: 0.5, desolate: 0.3, volcanic: 0.65 };
        const dT = climateOffset[this.climate] || 0;
        const dM = moistureScale[this.climate] || 1;

        // ── 3. Fill Climate flat maps ────────────────────────────────────────
        for (let y = 0; y < H; y++) {
            for (let x = 0; x < W; x++) {
                const idx = y * W + x;
                const h = this.heightMap[idx];
                const latDeg = ((H / 2 - y) / (H / 2)) * 90;
                const latAbs = Math.abs(latDeg);

                // Temperature
                const altCool = h > 0.5 ? (h - 0.5) * 62 : 0;
                const baseTemp = 32 - latAbs * 0.76 + dT - altCool;
                this.tempMap[idx] = Math.round(baseTemp);

                // Moisture
                const rawMoist = (noiseM.fbm(x / W * 5.2, y / H * 5.2, 4) + 1) / 2;
                const hadley = Math.sin((latAbs / 90) * Math.PI * 3) * 0.16;
                let moisture = Math.max(0, Math.min(1, rawMoist + hadley)) * dM;
                if (h > 0.65) moisture *= 0.55; // wind shadow
                this.moistureMap[idx] = Math.round(moisture * 100);

                // Aquifer & Magma
                this.aquiferMap[idx] = Math.max(5, Math.floor(moisture * 180 - (h > 0.65 ? 50 : 0)));
                this.magmaMap[idx] = Math.round(h * 60 + (this.climate === 'volcanic' ? 35 : 0));
            }
        }

        // ── 4. Biome Classification ──────────────────────────────────────────
        this._classifyBiomes();

        // ── 5. Hydrology ─────────────────────────────────────────────────────
        this._runHydrology();

        // ── 6. Politics ──────────────────────────────────────────────────────
        this._buildPolitics();

        // ── 7. Points of Interest ────────────────────────────────────────────
        this._scatterPOIs();
    }

    _classifyBiomes() {
        const W = this.width, H = this.height;
        const noiseAnom = new GradientNoise2D(new RNG(this.seed + '_Anom'));

        for (let y = 0; y < H; y++) {
            for (let x = 0; x < W; x++) {
                const idx = y * W + x;
                const h = this.heightMap[idx];
                const temp = this.tempMap[idx];
                const m = this.moistureMap[idx];
                const aquifer = this.aquiferMap[idx];
                let biome = 'Ocean';

                // ── Ocean / Sea ──
                if (h < 0.30) {
                    biome = h < 0.15 ? 'Trench' : 'Deep Ocean';
                } else if (h < 0.44) {
                    biome = 'Ocean';
                } else if (h < 0.49) {
                    if (temp > 22) biome = 'Coral Reef';
                    else if (temp < 14) biome = 'Kelp Forest';
                    else biome = 'Shallow Sea';
                } else {
                    // ── Land ──
                    let isAnomaly = false;
                    if (this.allowMagic) {
                        const magicFactor = (noiseAnom.fbm(x / W * 7, y / H * 7, 3) + 1) / 2;
                        if (magicFactor > 0.72) {
                            isAnomaly = true;
                            if (temp < -8) biome = (x % 2 === 0) ? 'Skyward Pillars' : 'Crystal Fields';
                            else if (temp > 24) biome = (x % 2 === 0) ? 'Obsidian Spireland' : 'Mana Wastes';
                            else if (m > 65) biome = (y % 2 === 0) ? 'Fey Wildwood' : 'Bioluminescent Jungle';
                            else if (m < 20) biome = (x % 2 === 0) ? 'Astral Rift' : 'Mana Wastes';
                            else biome = 'Shadow Glade';
                        }
                    }

                    if (!isAnomaly) {
                        if (temp < -15) {
                            biome = (h > 0.7) ? 'Glacier' : 'Ice Cap';
                        } else if (temp < -5) {
                            biome = (m > 40) ? 'Tundra' : 'Alpine Meadow';
                        } else if (h > 0.85) {
                            biome = (this.climate === 'volcanic' || temp > 20) ? 'Lava Field' : 'Snowcap';
                        } else if (h > 0.76) {
                            biome = (temp < 0) ? 'Snowcap' : 'Mountain';
                        } else if (h > 0.62) {
                            biome = (m < 20) ? 'Canyon' : 'Highland';
                        } else if (h > 0.57) {
                            biome = (m < 15) ? 'Mesa' : 'Plateau';
                        } else {
                            if (temp > 24) {
                                if (m < 15) biome = m < 8 ? 'Dune Sea' : 'Desert';
                                else if (m < 35) biome = 'Savanna';
                                else if (m > 75) biome = 'Rainforest';
                                else biome = 'Shrubland';
                            } else if (temp > 10) {
                                if (m < 12) biome = 'Desert';
                                else if (m < 30) biome = 'Grassland';
                                else if (m > 70) biome = 'Temperate Rainforest';
                                else if (m > 50) biome = 'Forest';
                                else biome = 'Shrubland';
                            } else {
                                if (m < 15) biome = 'Steppe';
                                else if (m > 65) biome = 'Taiga';
                                else if (m > 45) biome = 'Forest';
                                else biome = 'Grassland';
                            }
                        }

                        if (biome === 'Forest' || biome === 'Grassland' || biome === 'Shrubland') {
                            if (h < 0.52 && m > 65) {
                                biome = (temp > 16) ? 'Swamp' : 'Mangrove Swamp';
                            }
                        }

                        if ((biome === 'Desert' || biome === 'Dune Sea') && aquifer > 115) {
                            biome = 'Oasis';
                        }
                    }
                }

                this.biomeMap[idx] = BIOME_KEYS.indexOf(biome) !== -1 ? BIOME_KEYS.indexOf(biome) : 1;
            }
        }
    }

    _runHydrology() {
        const W = this.width, H = this.height;
        const dirs = [
            [0,1],[1,0],[0,-1],[-1,0],
            [1,1],[1,-1],[-1,1],[-1,-1]
        ];

        // 1. Gather potential high-mountain peaks/sources
        const sources = [];
        for (let y = 0; y < H; y++) {
            for (let x = 0; x < W; x++) {
                const idx = y * W + x;
                const h = this.heightMap[idx];
                const biome = BIOME_KEYS[this.biomeMap[idx]];
                if (h >= 0.72 || biome === 'Mountain' || biome === 'Snowcap' || biome === 'Volcano') {
                    sources.push({ x, y });
                }
            }
        }

        // Fallback if there are very few peaks
        if (sources.length < 50) {
            for (let y = 0; y < H; y++) {
                for (let x = 0; x < W; x++) {
                    const idx = y * W + x;
                    if (this.heightMap[idx] >= 0.60) {
                        sources.push({ x, y });
                    }
                }
            }
        }

        if (sources.length === 0) return;

        // 2. Generate rivers using downhill Dijkstra routing to water bodies
        const numRivers = Math.floor(W * 0.18);
        for (let i = 0; i < numRivers; i++) {
            const start = this.rng.pick(sources);
            
            const dist = new Float32Array(W * H).fill(Infinity);
            const parent = new Int32Array(W * H).fill(-1);
            
            const queue = [];
            const startIdx = start.y * W + start.x;
            dist[startIdx] = 0;
            queue.push({ x: start.x, y: start.y, idx: startIdx, cost: 0 });

            let endIdx = -1;
            
            while (queue.length > 0) {
                const curr = queue.shift();
                
                // Stop when we reach any water (ocean, sea, lake, or another river)
                const curH = this.heightMap[curr.idx];
                const curBiome = BIOME_KEYS[this.biomeMap[curr.idx]];
                if (curH < 0.49 || curBiome.includes('Ocean') || curBiome.includes('Sea') || this.riverMap[curr.idx] === 1 || this.lakeMap[curr.idx] === 1) {
                    endIdx = curr.idx;
                    break;
                }
                
                if (curr.cost > dist[curr.idx]) continue;

                for (const [dx, dy] of dirs) {
                    const nx = (curr.x + dx + W) % W;
                    const ny = Math.max(0, Math.min(H - 1, curr.y + dy));
                    const nIdx = ny * W + nx;
                    const nH = this.heightMap[nIdx];
                    
                    const diff = nH - curH;
                    // Steep downslope cost is extremely small, upslope cost has a massive penalty
                    const stepCost = 1.0 + (diff > 0 ? diff * 350.0 : diff * 2.0);
                    const nextCost = curr.cost + stepCost;

                    if (nextCost < dist[nIdx]) {
                        dist[nIdx] = nextCost;
                        parent[nIdx] = curr.idx;
                        
                        // Binary insert into priority queue
                        let l = 0, r = queue.length - 1, insertPos = queue.length;
                        while (l <= r) {
                            const m = (l + r) >> 1;
                            if (queue[m].cost > nextCost) {
                                insertPos = m;
                                r = m - 1;
                            } else {
                                l = m + 1;
                            }
                        }
                        queue.splice(insertPos, 0, { x: nx, y: ny, idx: nIdx, cost: nextCost });
                    }
                }
            }

            // Draw the path back to the starting peak
            if (endIdx !== -1) {
                let curr = endIdx;
                let pathLength = 0;
                while (curr !== -1) {
                    this.riverMap[curr] = 1;
                    curr = parent[curr];
                    pathLength++;
                    if (pathLength > 1000) break;
                }
            }
        }
    }

    _buildPolitics() {
        const W = this.width, H = this.height;
        const dirs = [[0,1],[1,0],[0,-1],[-1,0]];
        const numNations = this.rng.int(5, 9);
        const palettes = [
            '#66bb66','#6699cc','#e07a5f','#f2cc8f','#95d5b2',
            '#c77dff','#f4a261','#48cae4','#e63946','#2dc653',
        ];
        this.rng.shuffle(palettes);

        this.nations = [];
        this.citiesMap.clear();

        for (let i = 0; i < numNations; i++) {
            const capName = this.nameGen.capital();
            this.nations.push({
                name: this.nameGen.nation(),
                color: palettes[i % palettes.length],
                capital: capName,
                id: i,
            });
        }

        const queue = [];
        for (let i = 0; i < numNations; i++) {
            let cx = 0, cy = 0, found = false;
            for (let att = 0; att < 500; att++) {
                cx = this.rng.int(0, W - 1);
                cy = this.rng.int(0, H - 1);
                const idx = cy * W + cx;
                const h = this.heightMap[idx];
                const sBiome = BIOME_KEYS[this.biomeMap[idx]];

                if (h < 0.49 || ['Deep Ocean','Ocean','Shallow Sea','Mountain','Snowcap','Glacier','Volcano','Lava Field','Obsidian Spireland'].includes(sBiome)) continue;
                if (this.nationMap[idx] !== -1) continue;

                let nearWater = false;
                for (const [dx, dy] of dirs) {
                    const nx = (cx + dx + W) % W;
                    const ny = Math.max(0, Math.min(H - 1, cy + dy));
                    const nIdx = ny * W + nx;
                    if (this.heightMap[nIdx] < 0.49 || this.riverMap[nIdx] === 1) nearWater = true;
                }

                if (nearWater || att > 300) { found = true; break; }
            }

            const idx = cy * W + cx;
            this.nationMap[idx] = i;
            const pop = this.rng.int(30000, 500000);
            const cityObj = { name: this.nations[i].capital, isCapital: true, nationId: i, pop };
            this.citiesMap.set(`${cx},${cy}`, cityObj);
            this.cities.push({ name: this.nations[i].capital, x: cx, y: cy, nationId: i, isCapital: true, pop });
            queue.push({ x: cx, y: cy, nationId: i, cost: 0 });
        }

        while (queue.length > 0) {
            const curr = queue.shift();
            for (const [dx, dy] of dirs) {
                const nx = (curr.x + dx + W) % W;
                const ny = Math.max(0, Math.min(H - 1, curr.y + dy));
                const idx = ny * W + nx;
                const h = this.heightMap[idx];

                if (h < 0.49 || this.nationMap[idx] !== -1) continue;

                const cost = curr.cost + 1 + (h > 0.72 ? 8 : 0) + (this.riverMap[idx] ? 0.5 : 0);
                this.nationMap[idx] = curr.nationId;
                
                binaryInsert(queue, { x: nx, y: ny, nationId: curr.nationId, cost });
            }
        }

        const numTowns = Math.floor(W * 0.15);
        for (let i = 0; i < numTowns; i++) {
            const cx = this.rng.int(0, W - 1);
            const cy = this.rng.int(0, H - 1);
            const idx = cy * W + cx;
            const h = this.heightMap[idx];
            const sBiome = BIOME_KEYS[this.biomeMap[idx]];

            if (h < 0.49 || this.citiesMap.has(`${cx},${cy}`) || ['Mountain','Snowcap','Glacier','Volcano','Lava Field','Obsidian Spireland'].includes(sBiome)) continue;

            const name = this.nameGen.city();
            const isCity = this.rng.next() < 0.4;
            const pop = isCity ? this.rng.int(10000, 80000) : this.rng.int(200, 3000);
            const cityObj = { name, isCapital: false, nationId: this.nationMap[idx], pop };
            this.citiesMap.set(`${cx},${cy}`, cityObj);
            this.cities.push({ name, x: cx, y: cy, nationId: this.nationMap[idx], isCapital: false, pop });
        }
    }

    _scatterPOIs() {
        const W = this.width, H = this.height;
        const numPOIs = Math.floor(W * 0.08);
        this.pois = [];
        this.poisMap.clear();

        for (let i = 0; i < numPOIs; i++) {
            let px = 0, py = 0, idx = 0, h = 0, sBiome = '', att = 0;
            while (att < 200) {
                px = this.rng.int(0, W - 1);
                py = this.rng.int(0, H - 1);
                idx = py * W + px;
                h = this.heightMap[idx];
                sBiome = BIOME_KEYS[this.biomeMap[idx]];
                if (h >= 0.49 && !this.citiesMap.has(`${px},${py}`) && !this.poisMap.has(`${px},${py}`)) break;
                att++;
            }

            if (h < 0.49) continue;

            const candidates = POI_TYPES.filter(p => p.biomes.includes(sBiome));
            const poiType = candidates.length > 0 ? this.rng.pick(candidates) : this.rng.pick(POI_TYPES);
            const poiName = poiType.icon + ' ' + poiType.name;

            let minorFaction = "None";
            if (this.rng.next() < 0.4) {
                minorFaction = this.nameGen.factionName();
            }

            const poiSeed = `world_${this.seed}_${px}_${py}`;
            const proceduralDesc = generatePoiDescription(poiType.id, poiSeed, poiName);

            const poiObj = {
                type:  poiType.id,
                icon:  poiType.icon,
                label: poiType.name,
                name:  poiName,
                desc:  proceduralDesc,
                theme: poiType.theme,
                seed:  poiSeed,
                minorFaction
            };

            this.poisMap.set(`${px},${py}`, poiObj);
            this.pois.push({ ...poiObj, x: px, y: py });
        }
    }
}
